// test/features/auth/data/auth_service_test.dart
//
// Unit tests for AuthService — tests every Firebase method.
// Uses MockFirebaseAuth so NO real Firebase connection needed.
//
// Run: flutter test test/features/auth/data/auth_service_test.dart
import 'dart:async';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';

import 'package:insight/features/auth/data/auth_service.dart';

import 'auth_service_test.mocks.dart'; // auto-generated by build_runner

@GenerateMocks([FirebaseAuth, UserCredential, User])
void main() {
  late MockFirebaseAuth mockFirebaseAuth;
  late AuthService authService;

  setUp(() {
    mockFirebaseAuth = MockFirebaseAuth();
    authService = AuthService(firebaseAuth: mockFirebaseAuth);
  });

  // ════════════════════════════════════════════════════════════
  // signIn() tests
  // ════════════════════════════════════════════════════════════
  group('signIn()', () {
    test('TC-LG-01: Valid credentials — completes without error', () async {
      when(
        mockFirebaseAuth.signInWithEmailAndPassword(
          email: 'test@insight.com',
          password: 'Test@1234',
        ),
      ).thenAnswer((_) async => MockUserCredential());

      await expectLater(
        authService.signIn(email: 'test@insight.com', password: 'Test@1234'),
        completes,
      );
    });

    test('TC-LG-02: Wrong password — throws FirebaseAuthException', () async {
      when(
        mockFirebaseAuth.signInWithEmailAndPassword(
          email: 'test@insight.com',
          password: 'wrongpass',
        ),
      ).thenThrow(FirebaseAuthException(code: 'wrong-password'));

      await expectLater(
        authService.signIn(email: 'test@insight.com', password: 'wrongpass'),
        throwsA(isA<FirebaseAuthException>()),
      );
    });

    test('TC-LG-03: Unregistered email — throws user-not-found', () async {
      when(
        mockFirebaseAuth.signInWithEmailAndPassword(
          email: 'ghost@nowhere.com',
          password: 'Test@1234',
        ),
      ).thenThrow(FirebaseAuthException(code: 'user-not-found'));

      await expectLater(
        authService.signIn(email: 'ghost@nowhere.com', password: 'Test@1234'),
        throwsA(
          isA<FirebaseAuthException>().having(
            (e) => e.code,
            'code',
            'user-not-found',
          ),
        ),
      );
    });

    test('TC-LG-04: Email is trimmed before being sent to Firebase', () async {
      when(
        mockFirebaseAuth.signInWithEmailAndPassword(
          email: 'test@insight.com', // trimmed
          password: 'Test@1234',
        ),
      ).thenAnswer((_) async => MockUserCredential());

      // Pass email with spaces — your code does email.trim()
      await authService.signIn(
        email: '  test@insight.com  ',
        password: 'Test@1234',
      );

      // Verify Firebase was called with trimmed email, NOT the spaced one
      verify(
        mockFirebaseAuth.signInWithEmailAndPassword(
          email: 'test@insight.com',
          password: 'Test@1234',
        ),
      ).called(1);
    });
  });

  // ════════════════════════════════════════════════════════════
  // register() tests
  // ════════════════════════════════════════════════════════════
  group('register()', () {
    test(
      'TC-SU-01: Valid new email and password — registers successfully',
      () async {
        when(
          mockFirebaseAuth.createUserWithEmailAndPassword(
            email: 'newuser@insight.com',
            password: 'Test@1234',
          ),
        ).thenAnswer((_) async => MockUserCredential());

        await expectLater(
          authService.register(
            email: 'newuser@insight.com',
            password: 'Test@1234',
          ),
          completes,
        );
      },
    );

    test(
      'TC-SU-04: Already registered email — throws email-already-in-use',
      () async {
        when(
          mockFirebaseAuth.createUserWithEmailAndPassword(
            email: 'existing@insight.com',
            password: 'Test@1234',
          ),
        ).thenThrow(FirebaseAuthException(code: 'email-already-in-use'));

        await expectLater(
          authService.register(
            email: 'existing@insight.com',
            password: 'Test@1234',
          ),
          throwsA(
            isA<FirebaseAuthException>().having(
              (e) => e.code,
              'code',
              'email-already-in-use',
            ),
          ),
        );
      },
    );

    test('TC-SU-05: Weak password — throws weak-password error', () async {
      when(
        mockFirebaseAuth.createUserWithEmailAndPassword(
          email: 'test@insight.com',
          password: '123',
        ),
      ).thenThrow(FirebaseAuthException(code: 'weak-password'));

      await expectLater(
        authService.register(email: 'test@insight.com', password: '123'),
        throwsA(
          isA<FirebaseAuthException>().having(
            (e) => e.code,
            'code',
            'weak-password',
          ),
        ),
      );
    });

    test('TC-SU-06: Email is trimmed before being sent to Firebase', () async {
      when(
        mockFirebaseAuth.createUserWithEmailAndPassword(
          email: 'newuser@insight.com',
          password: 'Test@1234',
        ),
      ).thenAnswer((_) async => MockUserCredential());

      await authService.register(
        email: '  newuser@insight.com  ',
        password: 'Test@1234',
      );

      verify(
        mockFirebaseAuth.createUserWithEmailAndPassword(
          email: 'newuser@insight.com',
          password: 'Test@1234',
        ),
      ).called(1);
    });
  });

  // ════════════════════════════════════════════════════════════
  // sendPasswordResetEmail() tests
  // ════════════════════════════════════════════════════════════
  group('sendPasswordResetEmail()', () {
    test(
      'TC-FP-01: Valid registered email — reset email sent successfully',
      () async {
        when(
          mockFirebaseAuth.sendPasswordResetEmail(email: 'test@insight.com'),
        ).thenAnswer((_) async {});

        await expectLater(
          authService.sendPasswordResetEmail(email: 'test@insight.com'),
          completes,
        );
      },
    );

    test('TC-FP-02: Unregistered email — throws user-not-found', () async {
      when(
        mockFirebaseAuth.sendPasswordResetEmail(email: 'ghost@nowhere.com'),
      ).thenThrow(FirebaseAuthException(code: 'user-not-found'));

      await expectLater(
        authService.sendPasswordResetEmail(email: 'ghost@nowhere.com'),
        throwsA(isA<FirebaseAuthException>()),
      );
    });

    test('TC-FP-06: Email is trimmed before being sent to Firebase', () async {
      when(
        mockFirebaseAuth.sendPasswordResetEmail(email: 'test@insight.com'),
      ).thenAnswer((_) async {});

      await authService.sendPasswordResetEmail(email: '  test@insight.com  ');

      verify(
        mockFirebaseAuth.sendPasswordResetEmail(email: 'test@insight.com'),
      ).called(1);
    });
  });

  // ════════════════════════════════════════════════════════════
  // signOut() tests
  // ════════════════════════════════════════════════════════════
  group('signOut()', () {
    test('TC-HM-05: signOut — calls FirebaseAuth.signOut()', () async {
      when(mockFirebaseAuth.signOut()).thenAnswer((_) async {});

      await authService.signOut();

      verify(mockFirebaseAuth.signOut()).called(1);
    });
  });
}
