// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmJrbqc4uQeloMxr_6bPgvV8tEctSJE0Q',
    appId: '1:185315258538:web:66ec8ed8149a73ac4820d3',
    messagingSenderId: '185315258538',
    projectId: 'insight-64965',
    authDomain: 'insight-64965.firebaseapp.com',
    storageBucket: 'insight-64965.firebasestorage.app',
    measurementId: 'G-CM0EPCK9CZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVirZDobXhBxW_4AubQoatswHMuIPmzuc',
    appId: '1:185315258538:android:42b85bcd3e4d93354820d3',
    messagingSenderId: '185315258538',
    projectId: 'insight-64965',
    storageBucket: 'insight-64965.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUxgRgbDpdG1VKhI89LR23HcffYTCfOm8',
    appId: '1:185315258538:ios:21554b5d0c6626a64820d3',
    messagingSenderId: '185315258538',
    projectId: 'insight-64965',
    storageBucket: 'insight-64965.firebasestorage.app',
    iosBundleId: 'com.example.insight',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUxgRgbDpdG1VKhI89LR23HcffYTCfOm8',
    appId: '1:185315258538:ios:21554b5d0c6626a64820d3',
    messagingSenderId: '185315258538',
    projectId: 'insight-64965',
    storageBucket: 'insight-64965.firebasestorage.app',
    iosBundleId: 'com.example.insight',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmJrbqc4uQeloMxr_6bPgvV8tEctSJE0Q',
    appId: '1:185315258538:web:d6e937aec97d54e64820d3',
    messagingSenderId: '185315258538',
    projectId: 'insight-64965',
    authDomain: 'insight-64965.firebaseapp.com',
    storageBucket: 'insight-64965.firebasestorage.app',
    measurementId: 'G-KR7CS0D84P',
  );
}
